export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_SEARCH_TEXT: "SET_SEARCH_TEXT",
  SET_MY_SHOPPING_CART: "SET_MY_SHOPPING_CART",
  SET_CUSTOMER_DETAILS: "SET_CUSTOMER_DETAILS",
  SET_SHIPPING_DETAILS: "SET_SHIPPING_DETAILS",
  SET_CART_TOTAL_AMOUNT: "SET_CART_TOTAL_AMOUNT",
  SET_PAYMENT_STATUS: "SET_PAYMENT_STATUS",
  SET_PAYMENT_DETAILS: "SET_PAYMENT_DETAILS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_REGISTER_STATUS: "SET_REGISTER_STATUS",
  SET_PRODUCT_SOLD_RESPONSE: "SET_PRODUCT_SOLD_RESPONSE",
  SET_TODAY_HISTORY_DATA: "SET_TODAY_HISTORY_DATA",
  SET_WEEK_HISTORY_DATA: "SET_WEEK_HISTORY_DATA",
  SET_MONTH_HISTORY_DATA: "SET_MONTH_HISTORY_DATA",

  CALL_API_FOR_TODAY_DATA: "CALL_API_FOR_TODAY_DATA",
  CALL_API_FOR_WEEKLY_DATA: "CALL_API_FOR_WEEKLY_DATA",
  CALL_API_FOR_MONTHLY_DATA: "CALL_API_FOR_MONTHLY_DATA",

  // Admin
  SET_PRODUCT_FOR_DISCOUNT: "SET_PRODUCT_FOR_DISCOUNT",
};
