export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_SEARCH_TEXT: "SET_SEARCH_TEXT",
  SET_MY_SHOPPING_CART: "SET_MY_SHOPPING_CART",
  SET_CUSTOMER_DETAILS: "SET_CUSTOMER_DETAILS",
  SET_SHIPPING_DETAILS: "SET_SHIPPING_DETAILS",
};
